const PRODUCT_STATUS = {};

const ORDER_STATUS = {
  ORDER_PLACED: 'ORDER_PLACED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  ORDER_SHIPPED: 'ORDER_SHIPPED',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_CANCELED: 'ORDER_CANCELED'
};

const ORDER_STATUS_DB_ENUM = Object.values(ORDER_STATUS);

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CAPTURED: 'CAPTURED',
  RELEASED: 'RELEASED'
};

const PAYMENT_STATUS_DB_ENUM = Object.values(PAYMENT_STATUS);

module.exports = {
  PRODUCT_STATUS,
  ORDER_STATUS_DB_ENUM,
  ORDER_STATUS,
  PAYMENT_STATUS,
  PAYMENT_STATUS_DB_ENUM
};
